app.name = Mata dureewwan
theme_blue = Cuquliisa
theme_teal = Magariisa cuquliisa
theme_rose = Diimaa
theme_violet = Diimaa cuquliisa
theme_terracotta = Terracotta
theme_matcha = Matcha
theme_steel = Steel
